### ISSUE TITLE
Deprecated color codes

### ISSUE THREAD

**Issue by spncr** [stublag/yoyoexpert-dark#2]
Hi! I'm working with Andre to get some theme fixes working on his site.

It looks like the color variables in this theme were deprecated, so working on fix now

> :warning: The use of SCSS color variables (like $primary, $secondary` and so on) is deprecated. Discourse core uses CSS custom properties since August 2020 and we can recommend all existing themes switch SCSS variables to CSS custom properties. For complex color manipulations, see this guide.
from [the docs](https://meta.discourse.org/t/use-discourse-core-variables-in-your-theme/77551?silent=true)

Sidebar, would you be able to grant me access to this repo for I can work on it directly? Thanks!

**Comment by stublag** [comment]
Yep, I can grant you access right away 👍
